export class Member{
  id?: number
  name!: string
  office!: string
  consecration_date!: Date
  congregation!: string
  sector!: string
  regional!: string
  name_father!: string
  name_mother!: string
  date_birth!: Date
  naturalness!: string
  uf!: string
  sex!: string
  cep!: string
  address!: string
  neighborhood!: string
  city!: string
  country!: string
  fone_res!: string
  fone_cel!: string
  email!: string
  marital_status!: string
  date_wedding!: Date
  profession!: string
  cpf!: string
  rg!: string
  baptized_he!: string
  date_baptized_he!: Date
  date_baptized!: Date
  church!: string
  church_city!: string
  church_uf!: string
  date_admission!: Date
  date_conversion!: Date
  church_origin!: string
  church_origin_city!: string
  church_origin_city_uf!:string
  name_spouse!: string
  children!: string
  amount_son!: number
}
